name: Build

on:
  push:
    paths:
      - 'flake.lock'
      - '**/*.nix'
      - '**/*.cpp'
      - '**/*.hpp'
      - '**/*.yaml'
  pull_request:
    paths:
      - 'flake.lock'
      - '**/*.nix'
      - '**/*.cpp'
      - '**/*.hpp'
      - '**/*.yaml'

jobs:
  nix-build:
    name: Nix Flake Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - name: Nix Flake Check
        run: nix flake check -L
